name: CI/CD Orchestrator

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: read
  actions: write

jobs:
  trigger-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy App Infra Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy App Infra
          token: ${{ secrets.GITHUB_TOKEN }}

  trigger-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Run Unit Tests Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Run Unit Tests
          token: ${{ secrets.GITHUB_TOKEN }}

  wait-and-deploy:
    runs-on: ubuntu-latest
    needs: [trigger-infra, trigger-tests]  # Ensures this job runs after both workflows succeed
    steps:
      - name: Wait for successful completion
        run: echo "Both Deploy App Infra and Run Unit Tests completed successfully."
      
      - name: Trigger Final Deploy Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy .NET App to Elastic Beanstalk (Blue-Green + Manual Approval)
          token: ${{ secrets.GITHUB_TOKEN }}
