name: CI/CD Orchestrator

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: read
  actions: write

jobs:
  trigger-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy App Infra Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy App Infra
          token: ${{ secrets.GITHUB_TOKEN }}

  trigger-tests:
    runs-on: ubuntu-latest
    needs: trigger-infra 
    steps:
      - name: Trigger Run Unit Tests Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Run Unit Tests
          token: ${{ secrets.GITHUB_TOKEN }}

  wait-and-deploy:
    runs-on: ubuntu-latest
    needs: [trigger-infra, trigger-tests]  # Ensures this job runs after both workflows succeed
    steps:
      - name: Wait for successful completion
        run: echo "Both Deploy App Infra and Run Unit Tests completed successfully."

      - name: Determine the selected environment from commit message
        id: determine-env
        run: |
          # Extract environment from commit message
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MSG"

          # Match and set deploy environment
          DEPLOY_ENV_TG=$(echo "$COMMIT_MSG" | grep -oE '\[blue\]|\[green\]')
          
          if [[ -z "$DEPLOY_ENV_TG" ]]; then
            echo "No environment specified in commit message. Use '[blue]' or '[green]'"
            exit 1
          fi

          # Set the environment variable for downstream jobs
          echo "deploy_env=${DEPLOY_ENV_TG//[\[\]]/}" >> $GITHUB_ENV
          echo "Deploying to ${DEPLOY_ENV_TG//[\[\]]/} environment."

      - name: Trigger Final Deploy Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy .NET App to Elastic Beanstalk (Blue-Green + Manual Approval)
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          deploy_environment: ${{ env.deploy_env }}  # Pass the dynamic environment as an env variable