name: Deploy .NET App to Elastic Beanstalk (Blue-Green + Manual Approval)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      version_label: ${{ steps.create_version.outputs.version_label }}
      inactive_env_target: ${{ steps.determine-env.outputs.inactive_env_target }}
    env:
      DOTNET_VERSION: '9.0'
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
      APPLICATION_NAME: 'sample-eb-dotnet-app'
      PROD_ENV: 'sample-eb-dotnet-app-green'
      DEV_ENV: 'sample-eb-dotnet-app-blue'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish -c Release -r linux-x64 --self-contained true -o publish_output

    - name: Create Version Label
      id: create_version
      run: |
        VERSION_LABEL="ver-${{ github.run_id }}-${{ github.run_number }}"
        echo "VERSION_LABEL=$VERSION_LABEL" >> $GITHUB_ENV
        echo "version_label=$VERSION_LABEL" >> $GITHUB_OUTPUT

    - name: Zip publish output
      run: |
        cd publish_output
        zip -r ../app.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Upload ZIP to S3
      run: |
        aws s3 cp app.zip s3://${{ env.AWS_S3_BUCKET }}/app-${{ env.VERSION_LABEL }}.zip

    - name: Determine inactive environment
      id: determine-env
      run: |
        # Determine which environment is inactive (either Green or Blue)
        ACTIVE_GREEN_ENV=$(aws elasticbeanstalk describe-environments --application-name $APPLICATION_NAME --query "Environments[?EnvironmentName=='$PROD_ENV'].[Health]" --output text)
        ACTIVE_BLUE_ENV=$(aws elasticbeanstalk describe-environments --application-name $APPLICATION_NAME --query "Environments[?EnvironmentName=='$DEV_ENV'].[Health]" --output text)

        if [ "$ACTIVE_GREEN_ENV" != "Green" ]; then
          # Green is inactive, deploy to Green
          echo "inactive_env_target=${PROD_ENV}" >> $GITHUB_ENV
          echo "inactive_env_target=${PROD_ENV}" >> $GITHUB_OUTPUT
        else
          # Blue is inactive, deploy to Blue
          echo "inactive_env_target=${DEV_ENV}" >> $GITHUB_ENV
          echo "inactive_env_target=${DEV_ENV}" >> $GITHUB_OUTPUT
        fi

    - name: Deploy to target environment
      run: |
        aws elasticbeanstalk create-application-version \
          --application-name $APPLICATION_NAME \
          --version-label ${{ steps.create_version.outputs.version_label }} \
          --source-bundle S3Bucket=$AWS_S3_BUCKET,S3Key=app-${{ steps.create_version.outputs.version_label }}.zip

        aws elasticbeanstalk update-environment \
          --application-name $APPLICATION_NAME \
          --environment-name ${{ steps.determine-env.outputs.inactive_env_target }} \
          --version-label ${{ steps.create_version.outputs.version_label }}

    - name: Wait for target environment to be healthy
      run: |
        echo "Waiting for environment ${{ steps.determine-env.outputs.inactive_env_target }} to be healthy..."
        while true; do
          ENV_HEALTH=$(aws elasticbeanstalk describe-environments --application-name $APPLICATION_NAME --environment-name ${{ steps.determine-env.outputs.inactive_env_target }} --query "Environments[0].Health" --output text)
          if [ "$ENV_HEALTH" == "Green" ]; then
            echo "Environment ${{ steps.determine-env.outputs.inactive_env_target }} is healthy!"
            break
          elif [ "$ENV_HEALTH" == "Red" ]; then
            echo "Environment ${{ steps.determine-env.outputs.inactive_env_target }} is unhealthy! Exiting..."
            exit 1
          else
            echo "Environment ${{ steps.determine-env.outputs.inactive_env_target }} is not healthy yet. Waiting..."
            sleep 30
          fi
        done

  swap-cnames:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      APPLICATION_NAME: 'sample-eb-dotnet-app'
    steps:
    - name: Swap Blue-Green Environments
      run: |
        TARGET=${{ needs.build-and-deploy.outputs.inactive_env_target }}
        if [ "$TARGET" = "${{ secrets.EB_ENV_BLUE }}" ]; then
          SOURCE=${{ secrets.EB_ENV_BLUE }}
          DEST=${{ secrets.EB_ENV_GREEN }}
        else
          SOURCE=${{ secrets.EB_ENV_GREEN }}
          DEST=${{ secrets.EB_ENV_BLUE }}
        fi
        echo "Swapping CNAMEs: $SOURCE → $DEST"
        aws elasticbeanstalk swap-environment-cnames \
          --source-environment-name "$SOURCE" \
          --destination-environment-name "$DEST"
