name: swap blue-green

on:
    workflow_dispatch:
      inputs:
        environment:
          description: 'Which environment to swap to (blue/green)'
          default: 'blue'
    workflow_run:
      workflows: ["deploy .net app to elastic beanstalk"]
      types:
        - completed
  
jobs:
  swap_cnames:
    runs-on: ubuntu-latest
    env:
      DOTNET_VERSION: '9.0'
      AWS_REGION: ${{ secrets.AWS_REGION }}
      APP_SOLUTION_BUCKET: ${{ secrets.SOLUTION_S3_BUCKET }}
      APP_NAME: ${{ secrets.EB_APP_NAME }}
      ENV_GREEN: ${{ secrets.EB_ENV_GREEN }}
      ENV_BLUE: ${{ secrets.EB_ENV_BLUE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Swap Blue-Green Environments
        run: |
            # Get version labels
            BLUE_VERSION_LABEL=$(aws elasticbeanstalk describe-environments \
            --application-name $APP_NAME \
            --environment-names $ENV_BLUE \
            --query "Environments[0].VersionLabel" \
            --output text)
        
            GREEN_VERSION_LABEL=$(aws elasticbeanstalk describe-environments \
            --application-name $APP_NAME \
            --environment-names $ENV_GREEN \
            --query "Environments[0].VersionLabel" \
            --output text)
        
            echo "Blue version: $BLUE_VERSION_LABEL"
            echo "Green version: $GREEN_VERSION_LABEL"
        
            # Determine trigger type and target environment
            if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            DEPLOY_ENV_TG="${{ github.event.inputs.environment }}"
            echo "Manual trigger via workflow_dispatch: $DEPLOY_ENV_TG"
            else
            COMMIT_MSG=$(git log -1 --pretty=%B)
            echo "Commit message: $COMMIT_MSG"
            if [[ "$COMMIT_MSG" == *"[blue]"* ]]; then
                DEPLOY_ENV_TG="blue"
            elif [[ "$COMMIT_MSG" == *"[green]"* ]]; then
                DEPLOY_ENV_TG="green"
            else
                echo "No [blue] or [green] tag found in commit message. Aborting."
                exit 1
            fi
            echo "Auto trigger via workflow_run. Parsed environment: $DEPLOY_ENV_TG"
            fi
        
            # Define source and target environments based on desired deployment
            if [ "$DEPLOY_ENV_TG" == "blue" ]; then
            SOURCE_ENV=$ENV_BLUE
            TARGET_ENV=$ENV_GREEN
            elif [ "$DEPLOY_ENV_TG" == "green" ]; then
            SOURCE_ENV=$ENV_GREEN
            TARGET_ENV=$ENV_BLUE
            else
            echo "Invalid environment: $DEPLOY_ENV_TG"
            exit 1
            fi
        
            echo "Swapping CNAMEs: $SOURCE_ENV → $TARGET_ENV"
            aws elasticbeanstalk swap-environment-cnames \
            --source-environment-name "$SOURCE_ENV" \
            --destination-environment-name "$TARGET_ENV"
        
            ENV_CNAME=$(aws elasticbeanstalk describe-environments \
            --application-name $APP_NAME \
            --environment-names $TARGET_ENV \
            --query "Environments[0].CNAME" \
            --output text)
        
            echo "Live environment CNAME: $ENV_CNAME"
        