name: Run Unit Tests

on:
  # push:
  #   branches:
  #     - main  # Trigger on commits to main branch
  workflow_run:
    workflows: ["Deploy App Infra"]
    types:
      - completed

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: src/app

      - name: Run Unit Tests
        run: dotnet test --no-restore
        working-directory: src/app